### PR TITLE
Adds mix formatter

### PR DESCRIPTION
**Pull request by securingsincity**
This is mostly ripped from vscode-exfmt.

### CODE REVIEW

**Comment by fr1zle** [comment]
Thanks, let me know once you are ready so i can review and merge. Feel free to add yourself to the README as well :+1:

**Comment by securingsincity** [comment]
I thihk this is good now @fr1zle  Let me know if you want me to add anything but it should be working.

**Comment by fr1zle** [comment]
Looking good, will try to find a good way to test elixir 1.6 and then merge :+1:

**Comment by piersadrian** [comment]
Just wanted to ping here and see if there's anything I can do to help move this along. Thanks!

**Comment by securingsincity** [comment]
@fr1zle this should finally be ready. sorry for the delay.

**Comment by fr1zle** [comment]
Nice, I hope to have this merged by the weekend!

**Comment by fr1zle** [comment]
Thanks again, and sorry for the wait, the end of the year is pretty busy for me.

**Comment by lleger** [comment]
@fr1zle Excited to use this in my projects! Any idea when a new release will go out including this PR?

**Comment by fr1zle** [comment]
@lleger Currently planning to release a new version by the end of january. You can observe the milestone i created :-)

**Comment by odarriba** [comment]
Hey! Any chance of releasing this before all that features are finished? Elixir 1.6.0 is already out!

Thanks

**Pull request merged**
