### PR TITLE
Rewrite and lint - cleanup

### PR DESCRIPTION
**Pull request by untra**
I cleaned up the original PR #74 here to focus just on the linter and setting up the linter rules. Here is all the work, complete and operational :+1:

### CODE REVIEW

**Comment by untra** [comment]
You may want to take a look at the CI system there, @fr1zle .
Thanks for looking this over!

**Comment by untra** [comment]
I added one more commit because I forgot to add the elixirSense subscriptions to the vscode language providers. If you clone down my branch you should see parity and functionality with the current plugin. Cheers!

**Comment by fr1zle** [comment]
@untra can you rebase this agains #80 ? 
I will then pull this, after releasing #80 for some bugfixes.

**Comment by untra** [comment]
@fr1zle rebased and tests passing :+1:

**Comment by fr1zle** [comment]
Merged, thanks so much :-)

**Comment by fr1zle** [comment]
@untra i just notice, that this somehow broke autocomplete. When pressing '.' after typing a module name it doesnt suggest any function anymore. Even pressing ctrl+space won't trigger it.

Any idea how that happened?

**Comment by PotterDai** [comment]
Thank you for the cleaning!
However I just checked the file:
https://github.com/fr1zle/vscode-elixir/blob/master/src/elixirSenseDefinitionProvider.ts#L37
and found this windows go to definition bug be reversed back.

Just replace:
`const [filePath, lineNumberStr] = result.split(':');`
with
`const filePath = result.substring(0, result.lastIndexOf(":")); `
`const lineNumberStr = result.substring(result.lastIndexOf(":") + 1, result.length);`

Thank you very much! = )

**Comment by untra** [comment]
@fr1zle I opened a new PR to refactor the elixirSenseClient to use promises. I'll add changes to look into the missing autocomplete later tonight. Whoops! #81
@PotterDai I put the goto definition fix for windows back in. Good catch :+1:

**Pull request merged**
