### PR TITLE
Fixes for warnings in Elixir 1.4.2

### PR DESCRIPTION
**Pull request by samuelsuarezsanchez**
With the latest version of Elixir there are multiple warnings triggered by `alchemist-server`. This PR contains small changes in the code to avoid those warnings and that do not affect the existing functionality.

Ideally this PR would be proposed in the `alchemist-server` repo itself, however I have noticed the `master` branch in that repo differs quite a lot from the one we depend on here (e.g. `alchemist-server` does not support passing files as parameters as the in-built parser has been removed).

This would be just a patch to keep this extension working while a more permanent solution is implemented.

### CODE REVIEW

**Comment by fr1zle** [comment]
lgtm @mat-mcloughlin 

Thanks for contributing :-)

**Comment by mat-mcloughlin** [comment]
@fr1zle if you are happy you do have permission to merge it in :)

**Comment by fr1zle** [comment]
@samuelsuarezsanchez after merging #24 this PR has conflicts, would you mind resolving them?

**Comment by samuelsuarezsanchez** [comment]
@fr1zle Done.

**Comment by fr1zle** [comment]
And merged, thanks again for contributing @samuelsuarezsanchez

**Pull request merged**
